dist: bionic
language: python

sudo: required

services:
  - docker

python:
  - 3.7

env:
  - DJANGO=2.2.7

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

before_script:
  - python manage.py check
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source=base,registration,entry_logs,innovacer_summergeeks_assignment manage.py test

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - coderdude1999@gmail.com
    on_success: change
    on_failure: always

