# Generated by Django 2.2.7 on 2019-11-20 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=10)),
                ('address', models.TextField()),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout_time', models.DateTimeField(null=True)),
                ('visitor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Visitor')),
            ],
            options={
                'ordering': ['checkin_time'],
            },
        ),
    ]
