# Generated by Django 2.2.7 on 2019-11-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='unique_token_number',
            field=models.CharField(default='iurtF', max_length=4),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='public_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
