# Generated by Django 2.2.7 on 2019-11-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_logs', '0002_auto_20191120_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='unique_token_number',
            field=models.CharField(default='00868', max_length=4),
        ),
    ]
