# Generated by Django 2.2.7 on 2019-11-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_logs', '0003_auto_20191120_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='unique_token_number',
            field=models.CharField(default='66487', max_length=4),
        ),
    ]
