# Generated by Django 2.2.7 on 2019-11-20 20:23

from django.db import migrations, models
import entry_logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_logs', '0004_auto_20191121_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='unique_token_number',
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='unique_token',
            field=models.CharField(default=entry_logs.models.get_visitor_token, max_length=4),
        ),
    ]
