# Generated by Django 2.2.7 on 2019-11-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20191121_0046'),
        ('entry_logs', '0005_auto_20191121_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.Host'),
            preserve_default=False,
        ),
    ]
