"""
Django settings for innovacer_summergeeks_assignment project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

try:
    from . import private_settings as external_settings
    print("Using Private settings")

except ImportError:
    from . import public_settings as external_settings
    print("Using Public Settings")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = external_settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = external_settings.DEBUG

ALLOWED_HOSTS = external_settings.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'base',
    'registration',
    'entry_logs'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'innovacer_summergeeks_assignment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'innovacer_summergeeks_assignment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = external_settings.DATABASES


AUTH_USER_MODEL = 'registration.User'
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = 'entry_logs:logs'
LOGIN_URL = "registration:login"
LOGOUT_REDIRECT_URL = "/"

SENDGRID_SANDBOX_MODE_IN_DEBUG = external_settings.SENDGRID_SANDBOX_MODE_IN_DEBUG
SENDGRID_API_KEY = external_settings.SENDGRID_API_KEY

EMAIL_BACKEND = external_settings.EMAIL_BACKEND
EMAIL_HOST = external_settings.EMAIL_HOST
EMAIL_PORT = external_settings.EMAIL_PORT
EMAIL_USE_TLS = external_settings.EMAIL_USE_TLS
EMAIL_HOST_USER = external_settings.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
DEFAULT_EMAIL_SENDER = "entrypoint@gatekeepers.com"
PUBLIC_ID_LENGTH = external_settings.PUBLIC_ID_LENGTH
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
