# Generated by Django 2.2.7 on 2019-11-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('targets', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
